---
title: "Data in space and time!"
author: "The IDDS 2201 team"
date: "4/27/2022"
output: html_document
---

An in-class code-along adventure exploring ways to visualize data in space and through time! 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Packages

The following packages may be useful today. 

```{r}
library(tidyverse) # data exploration toolset
library(gganimate) # visualizing through time https://gganimate.com/
library(lubridate) # exploring time data 
library(sf)        # makes mapping easy...er
library(cartogram) # transform spatial objects
library(rayshader) # shine a light on data
library(rgl)       # render data viz interactively 
library(viridis)   # nice color palettes
library(DT)        # interactive data tables
library(plotly)    # interactive data plots
library(maps)      # map tools
```



# Data

## State population

```{r}
# ran tidycensus::census_api_key() first with key sent to inbox.
# More info: https://walker-data.com/tidycensus/articles/basic-usage.html

## Ran this once and commented out so I do not have to keep bothering
## the API
# state_pop <-
#   tidycensus::get_acs(geography = "state",
#           variables = "B01003_001",
#           year = 2018,
#           geometry = F)
# readr::write_rds(state_pop,file = "data/state_pop.rds")
state_pop <- readr::read_rds(file = "data/state_pop.rds")

```

## COVID cases


```{r}
covid_2020 <- read_csv("https://github.com/nytimes/covid-19-data/raw/master/rolling-averages/us-counties-2020.csv")
covid_2021 <- read_csv("https://github.com/nytimes/covid-19-data/raw/master/rolling-averages/us-counties-2021.csv")
covid_2022 <- read_csv("https://github.com/nytimes/covid-19-data/raw/master/rolling-averages/us-counties-2022.csv")

glimpse(covid_2020)
glimpse(covid_2021)
glimpse(covid_2022)

# they all look the same! (columns and data types!)

covid_data_all <- rbind(covid_2020,covid_2021,covid_2022)
```





```{r}
summary(covid_data_all$cases_avg_per_100k)
```


```{r}
covid_data_all %>%
  filter(state == "New York") %>%
  ggplot() + 
  geom_line(aes(x=date,y=cases_avg, color = county))
```






```{r}
usa_county_map <- maps::map("county",fill = T,plot = F)


usa_county_sf <- sf::st_as_sf(usa_county_map) %>%
  sf::st_transform(crs = 4236)
```



```{r}
covid_case_NY <- covid_data_all %>%
  filter(state == "New York")


covid_case_NY <- covid_case_NY %>%
  mutate(state_lower = tolower(state)) %>%
  mutate(county_lower = tolower(county)) %>%
  mutate(state_county = paste(state_lower,county_lower,sep = ","))
```


```{r}
ny_data_and_map <- left_join(x = usa_county_sf,y=covid_case_NY,by=c("ID"="state_county"))
```



```{r}
ny_data_and_map %>%
  filter(date == "2022-04-01") %>%
  ggplot() + 
  geom_sf(aes(fill=cases_avg)) + 
  scale_fill_viridis_c("plasma")
```





```{r}
covid_by_state <- covid_data_all %>%
  group_by(date,state) %>%
  summarize(total_avg_cases  = sum(cases_avg)) %>%
  ungroup()
```


```{r}
usa_state_map <- maps::map("state",fill = T,plot = F)


usa_state_sf <- sf::st_as_sf(usa_state_map) %>%
  sf::st_transform(crs = 4236)
```



```{r}
covid_by_state <- covid_by_state %>%
  mutate(state_lower = tolower(state))
```


```{r}
usa_map_and_data <- left_join(x = usa_state_sf, y=covid_by_state ,by = c("ID"="state_lower"))
```

```{r}
my_date <- "2021-12-27"

usa_map_and_data %>%
  filter(date == my_date) %>%
  ggplot() + 
  geom_sf(aes(fill=total_avg_cases)) + 
  scale_fill_viridis("plasma")

```


```{r}
my_map <- usa_map_and_data %>%
  filter(date == my_date) %>%
  ggplot() + 
  geom_sf(aes(fill=total_avg_cases, text = ID)) + 
  scale_fill_viridis("plasma")


plotly::ggplotly(my_map)
```

